name: Build Electron App

# 触发条件：
# 1. 当有代码推送到 main 分支时
# 2. 允许在 GitHub Actions 页面手动触发
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    # 在 Windows, macOS, 和 Linux 三个平台上并行运行
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      # 第1步：检出您的代码
      - name: Check out git repository
        uses: actions/checkout@v4

      # 第2步：设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # 第3步：安装依赖（针对不同平台）
      - name: Install dependencies on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libsqlite3-dev
          npm ci

      - name: Install dependencies on macOS and Windows
        if: runner.os != 'Linux'
        run: npm ci

      # 第4步：执行打包和构建命令
      - name: Build distributable
        run: npm run make
      
      # 第5步：将生成的安装包作为临时附件(Artifact)上传
      # 您可以在工作流运行结束后下载这些附件
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          # 为每个平台的附件创建一个清晰的名称
          name: ${{ github.event.repository.name }}-${{ matrix.os }}-build
          # 上传 out/make 目录下的所有内容
          path: ./out/make/**/*